//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.42000
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace Fastighetsrapport.Models.Belagenhetsadress
{

    // 
    // This source code was auto-generated by xsd, Version=4.6.1055.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/gml/3.2")]
    [System.Xml.Serialization.XmlRootAttribute("name", Namespace="http://www.opengis.net/gml/3.2", IsNullable=false)]
    public partial class CodeType {
    
        private string codeSpaceField;
    
        private string valueField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string codeSpace {
            get {
                return this.codeSpaceField;
            }
            set {
                this.codeSpaceField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://namespace.lantmateriet.se/distribution/produkter/belagenhetsadress/v4.1.1")]
    public partial class DistrikttillhorighetType {
    
        private string distriktskodField;
    
        private string distriktsnamnField;
    
        /// <remarks/>
        public string distriktskod {
            get {
                return this.distriktskodField;
            }
            set {
                this.distriktskodField = value;
            }
        }
    
        /// <remarks/>
        public string distriktsnamn {
            get {
                return this.distriktsnamnField;
            }
            set {
                this.distriktsnamnField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://namespace.lantmateriet.se/distribution/produkter/belagenhetsadress/v4.1")]
    public partial class RegisterenhetsreferensType {
    
        private string objektidentitetField;
    
        /// <remarks/>
        public string objektidentitet {
            get {
                return this.objektidentitetField;
            }
            set {
                this.objektidentitetField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://namespace.lantmateriet.se/distribution/produkter/belagenhetsadress/v4.1")]
    public partial class AdressattAnlaggningType {
    
        private AdressattAnlaggningstypType anlaggningstypField;
    
        private string anlaggningstextField;
    
        /// <remarks/>
        public AdressattAnlaggningstypType anlaggningstyp {
            get {
                return this.anlaggningstypField;
            }
            set {
                this.anlaggningstypField = value;
            }
        }
    
        /// <remarks/>
        public string anlaggningstext {
            get {
                return this.anlaggningstextField;
            }
            set {
                this.anlaggningstextField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://namespace.lantmateriet.se/distribution/produkter/belagenhetsadress/v4.1")]
    public enum AdressattAnlaggningstypType {
    
        /// <remarks/>
        Avloppspumpstation,
    
        /// <remarks/>
        Brygga,
    
        /// <remarks/>
        Idrottsanläggning,
    
        /// <remarks/>
        Småbåtshamn,
    
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Tele- och radiomast")]
        Teleochradiomast,
    
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Transformator, transformatorstation, nätstation")]
        Transformatortransformatorstationnätstation,
    
        /// <remarks/>
        Vattentäkt,
    
        /// <remarks/>
        Återvinningsstation,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://namespace.lantmateriet.se/distribution/produkter/belagenhetsadress/v4.1")]
    public partial class AdressplatsanmarkningType {
    
        private AdressplatsanmarkningstypType anmarkningstypField;
    
        private string anmarkningstextField;
    
        /// <remarks/>
        public AdressplatsanmarkningstypType anmarkningstyp {
            get {
                return this.anmarkningstypField;
            }
            set {
                this.anmarkningstypField = value;
            }
        }
    
        /// <remarks/>
        public string anmarkningstext {
            get {
                return this.anmarkningstextField;
            }
            set {
                this.anmarkningstextField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://namespace.lantmateriet.se/distribution/produkter/belagenhetsadress/v4.1")]
    public enum AdressplatsanmarkningstypType {
    
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Angöringsplats för taxi")]
        Angöringsplatsförtaxi,
    
        /// <remarks/>
        Busshållplats,
    
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Järnvägsstation/hållplats")]
        Järnvägsstationhållplats,
    
        /// <remarks/>
        Kajplats,
    
        /// <remarks/>
        Spårvagnshållplats,
    
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Stoppställe för postutdelning")]
        Stoppställeförpostutdelning,
    
        /// <remarks/>
        Tunnelbanestationsnedgång,
    
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Övrig anmärkning")]
        Övriganmärkning,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://namespace.lantmateriet.se/distribution/produkter/belagenhetsadress/v4.1")]
    public partial class KommunType {
    
        private string kommunkodField;
    
        private string kommunnamnField;
    
        /// <remarks/>
        public string kommunkod {
            get {
                return this.kommunkodField;
            }
            set {
                this.kommunkodField = value;
            }
        }
    
        /// <remarks/>
        public string kommunnamn {
            get {
                return this.kommunnamnField;
            }
            set {
                this.kommunnamnField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GardsadressomradeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(KommundelType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AdressomradeType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://namespace.lantmateriet.se/distribution/produkter/belagenhetsadress/v4.1")]
    public abstract partial class UtbytesobjektType {
    
        private string objektidentitetField;
    
        private int objektversionField;
    
        private System.DateTime versionGiltigFranField;
    
        private bool versionGiltigFranFieldSpecified;
    
        /// <remarks/>
        public string objektidentitet {
            get {
                return this.objektidentitetField;
            }
            set {
                this.objektidentitetField = value;
            }
        }
    
        /// <remarks/>
        public int objektversion {
            get {
                return this.objektversionField;
            }
            set {
                this.objektversionField = value;
            }
        }
    
        /// <remarks/>
        public System.DateTime versionGiltigFran {
            get {
                return this.versionGiltigFranField;
            }
            set {
                this.versionGiltigFranField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool versionGiltigFranSpecified {
            get {
                return this.versionGiltigFranFieldSpecified;
            }
            set {
                this.versionGiltigFranFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://namespace.lantmateriet.se/distribution/produkter/belagenhetsadress/v4.1")]
    public partial class GardsadressomradeType : UtbytesobjektType {
    
        private string faststalltNamnField;
    
        private string ortidField;
    
        private ObjektstatusType objektstatusField;
    
        private AdressomradeType adressomradeField;
    
        /// <remarks/>
        public string faststalltNamn {
            get {
                return this.faststalltNamnField;
            }
            set {
                this.faststalltNamnField = value;
            }
        }
    
        /// <remarks/>
        public string ortid {
            get {
                return this.ortidField;
            }
            set {
                this.ortidField = value;
            }
        }
    
        /// <remarks/>
        public ObjektstatusType objektstatus {
            get {
                return this.objektstatusField;
            }
            set {
                this.objektstatusField = value;
            }
        }
    
        /// <remarks/>
        public AdressomradeType Adressomrade {
            get {
                return this.adressomradeField;
            }
            set {
                this.adressomradeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://namespace.lantmateriet.se/distribution/produkter/belagenhetsadress/v4.1")]
    public enum ObjektstatusType {
    
        /// <remarks/>
        Planerad,
    
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Gällande under utredning")]
        Gällandeunderutredning,
    
        /// <remarks/>
        Gällande,
    
        /// <remarks/>
        Avregistrerad,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://namespace.lantmateriet.se/distribution/produkter/belagenhetsadress/v4.1")]
    public partial class AdressomradeType : UtbytesobjektType {
    
        private string faststalltNamnField;
    
        private string ortidField;
    
        private AdressomradestypType adressomradestypField;
    
        private ObjektstatusType objektstatusField;
    
        private KommundelType kommundelField;
    
        /// <remarks/>
        public string faststalltNamn {
            get {
                return this.faststalltNamnField;
            }
            set {
                this.faststalltNamnField = value;
            }
        }
    
        /// <remarks/>
        public string ortid {
            get {
                return this.ortidField;
            }
            set {
                this.ortidField = value;
            }
        }
    
        /// <remarks/>
        public AdressomradestypType adressomradestyp {
            get {
                return this.adressomradestypField;
            }
            set {
                this.adressomradestypField = value;
            }
        }
    
        /// <remarks/>
        public ObjektstatusType objektstatus {
            get {
                return this.objektstatusField;
            }
            set {
                this.objektstatusField = value;
            }
        }
    
        /// <remarks/>
        public KommundelType Kommundel {
            get {
                return this.kommundelField;
            }
            set {
                this.kommundelField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://namespace.lantmateriet.se/distribution/produkter/belagenhetsadress/v4.1")]
    public enum AdressomradestypType {
    
        /// <remarks/>
        Gatuadressområde,
    
        /// <remarks/>
        Metertalsadressområde,
    
        /// <remarks/>
        Byadressområde,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://namespace.lantmateriet.se/distribution/produkter/belagenhetsadress/v4.1")]
    public partial class KommundelType : UtbytesobjektType {
    
        private string faststalltNamnField;
    
        private string ortidField;
    
        private ObjektstatusType objektstatusField;
    
        private KommunType kommunField;
    
        /// <remarks/>
        public string faststalltNamn {
            get {
                return this.faststalltNamnField;
            }
            set {
                this.faststalltNamnField = value;
            }
        }
    
        /// <remarks/>
        public string ortid {
            get {
                return this.ortidField;
            }
            set {
                this.ortidField = value;
            }
        }
    
        /// <remarks/>
        public ObjektstatusType objektstatus {
            get {
                return this.objektstatusField;
            }
            set {
                this.objektstatusField = value;
            }
        }
    
        /// <remarks/>
        public KommunType Kommun {
            get {
                return this.kommunField;
            }
            set {
                this.kommunField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://namespace.lantmateriet.se/distribution/produkter/belagenhetsadress/v4.1")]
    public partial class AdressplatsnamnType {
    
        private string popularnamnField;
    
        private string ortidField;
    
        /// <remarks/>
        public string popularnamn {
            get {
                return this.popularnamnField;
            }
            set {
                this.popularnamnField = value;
            }
        }
    
        /// <remarks/>
        public string ortid {
            get {
                return this.ortidField;
            }
            set {
                this.ortidField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LinearRingType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/gml/3.2")]
    public abstract partial class AbstractRingType {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://namespace.lantmateriet.se/distribution/produkter/belagenhetsadress/v4.1")]
    public partial class AdressplatsbeteckningType {
    
        private object[] itemsField;
    
        private ItemsChoiceType[] itemsElementNameField;
    
        private bool avvikerFranStandardenField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("adressplatsnummer", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("avvikandeAdressplatsbeteckning", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("bokstavstillagg", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("lagestillagg", typeof(LagestillaggType))]
        [System.Xml.Serialization.XmlElementAttribute("lagestillaggsnummer", typeof(int))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    
        /// <remarks/>
        public bool avvikerFranStandarden {
            get {
                return this.avvikerFranStandardenField;
            }
            set {
                this.avvikerFranStandardenField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://namespace.lantmateriet.se/distribution/produkter/belagenhetsadress/v4.1")]
    public enum LagestillaggType {
    
        /// <remarks/>
        UH,
    
        /// <remarks/>
        UV,
    
        /// <remarks/>
        U,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://namespace.lantmateriet.se/distribution/produkter/belagenhetsadress/v4.1", IncludeInSchema=false)]
    public enum ItemsChoiceType {
    
        /// <remarks/>
        adressplatsnummer,
    
        /// <remarks/>
        avvikandeAdressplatsbeteckning,
    
        /// <remarks/>
        bokstavstillagg,
    
        /// <remarks/>
        lagestillagg,
    
        /// <remarks/>
        lagestillaggsnummer,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://namespace.lantmateriet.se/distribution/produkter/belagenhetsadress/v4.1")]
    public partial class AdressplatsattributType {
    
        private AdressplatsbeteckningType adressplatsbeteckningField;
    
        private AdressplatstypType adressplatstypField;
    
        private AdressplatspunktlageType insamlingslageField;
    
        private PointPropertyType adressplatspunktField;
    
        private BelagenhetsadresstatusType statusForBelagenhetsadressField;
    
        private int postnummerField;
    
        private bool postnummerFieldSpecified;
    
        private string postortField;
    
        /// <remarks/>
        public AdressplatsbeteckningType Adressplatsbeteckning {
            get {
                return this.adressplatsbeteckningField;
            }
            set {
                this.adressplatsbeteckningField = value;
            }
        }
    
        /// <remarks/>
        public AdressplatstypType adressplatstyp {
            get {
                return this.adressplatstypField;
            }
            set {
                this.adressplatstypField = value;
            }
        }
    
        /// <remarks/>
        public AdressplatspunktlageType insamlingslage {
            get {
                return this.insamlingslageField;
            }
            set {
                this.insamlingslageField = value;
            }
        }
    
        /// <remarks/>
        public PointPropertyType Adressplatspunkt {
            get {
                return this.adressplatspunktField;
            }
            set {
                this.adressplatspunktField = value;
            }
        }
    
        /// <remarks/>
        public BelagenhetsadresstatusType statusForBelagenhetsadress {
            get {
                return this.statusForBelagenhetsadressField;
            }
            set {
                this.statusForBelagenhetsadressField = value;
            }
        }
    
        /// <remarks/>
        public int postnummer {
            get {
                return this.postnummerField;
            }
            set {
                this.postnummerField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool postnummerSpecified {
            get {
                return this.postnummerFieldSpecified;
            }
            set {
                this.postnummerFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        public string postort {
            get {
                return this.postortField;
            }
            set {
                this.postortField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://namespace.lantmateriet.se/distribution/produkter/belagenhetsadress/v4.1")]
    public enum AdressplatstypType {
    
        /// <remarks/>
        Gatuadressplats,
    
        /// <remarks/>
        Metertalsadressplats,
    
        /// <remarks/>
        Byadressplats,
    
        /// <remarks/>
        Gårdsadressplats,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://namespace.lantmateriet.se/distribution/produkter/belagenhetsadress/v4.1")]
    public enum AdressplatspunktlageType {
    
        /// <remarks/>
        Byggnad,
    
        /// <remarks/>
        Ingång,
    
        /// <remarks/>
        Infart,
    
        /// <remarks/>
        Tomtplats,
    
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Ungefärligt lägesbestämd")]
        Ungefärligtlägesbestämd,
    
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Övrigt läge")]
        Övrigtläge,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/gml/3.2")]
    [System.Xml.Serialization.XmlRootAttribute("pointProperty", Namespace="http://www.opengis.net/gml/3.2", IsNullable=false)]
    public partial class PointPropertyType {
    
        private PointType pointField;
    
        /// <remarks/>
        public PointType Point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/gml/3.2")]
    [System.Xml.Serialization.XmlRootAttribute("Point", Namespace="http://www.opengis.net/gml/3.2", IsNullable=false)]
    public partial class PointType : AbstractGeometricPrimitiveType {
    
        private DirectPositionType posField;
    
        /// <remarks/>
        public DirectPositionType pos {
            get {
                return this.posField;
            }
            set {
                this.posField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/gml/3.2")]
    [System.Xml.Serialization.XmlRootAttribute("pos", Namespace="http://www.opengis.net/gml/3.2", IsNullable=false)]
    public partial class DirectPositionType {

        private double[] coordinates;

        [System.Xml.Serialization.XmlIgnore]
        public double[] Coordinates
        {

            get { return this.coordinates; }
            set { this.coordinates = value; }
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        public string Text
        {
            get
            {
                return Fastighetsrapport.Util.GeometryParser.ConvertDoubleArrayToString(this.coordinates);
            }
            set
            {
                this.coordinates = Fastighetsrapport.Util.GeometryParser.ConvertStringToDoubleArray(value);
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractSurfaceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PolygonType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractCurveType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LineStringType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PointType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/gml/3.2")]
    public abstract partial class AbstractGeometricPrimitiveType : AbstractGeometryType {
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractGeometricAggregateType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MultiSurfaceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MultiCurveType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MultiPointType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractGeometricPrimitiveType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractSurfaceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PolygonType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractCurveType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LineStringType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PointType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/gml/3.2")]
    public abstract partial class AbstractGeometryType : AbstractGMLType {
    
        private string srsNameField;
    
        private string srsDimensionField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string srsName {
            get {
                return this.srsNameField;
            }
            set {
                this.srsNameField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string srsDimension {
            get {
                return this.srsDimensionField;
            }
            set {
                this.srsDimensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractGeometryType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractGeometricAggregateType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MultiSurfaceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MultiCurveType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MultiPointType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractGeometricPrimitiveType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractSurfaceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PolygonType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractCurveType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LineStringType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PointType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractFeatureType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BelagenhetsadressType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BelagenhetsadressResponseType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/gml/3.2")]
    public abstract partial class AbstractGMLType {
    
        private string descriptionField;
    
        private CodeType[] nameField;
    
        private string idField;
    
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("name")]
        public CodeType[] name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BelagenhetsadressType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BelagenhetsadressResponseType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/gml/3.2")]
    public abstract partial class AbstractFeatureType : AbstractGMLType {
    
        private BoundingShapeType boundedByField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BoundingShapeType boundedBy {
            get {
                return this.boundedByField;
            }
            set {
                this.boundedByField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/gml/3.2")]
    [System.Xml.Serialization.XmlRootAttribute("boundedBy", Namespace="http://www.opengis.net/gml/3.2", IsNullable=true)]
    public partial class BoundingShapeType {
    
        private EnvelopeType envelopeField;
    
        /// <remarks/>
        public EnvelopeType Envelope {
            get {
                return this.envelopeField;
            }
            set {
                this.envelopeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/gml/3.2")]
    [System.Xml.Serialization.XmlRootAttribute("Envelope", Namespace="http://www.opengis.net/gml/3.2", IsNullable=false)]
    public partial class EnvelopeType {
    
        private DirectPositionType lowerCornerField;
    
        private DirectPositionType upperCornerField;
    
        private string srsNameField;
    
        /// <remarks/>
        public DirectPositionType lowerCorner {
            get {
                return this.lowerCornerField;
            }
            set {
                this.lowerCornerField = value;
            }
        }
    
        /// <remarks/>
        public DirectPositionType upperCorner {
            get {
                return this.upperCornerField;
            }
            set {
                this.upperCornerField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string srsName {
            get {
                return this.srsNameField;
            }
            set {
                this.srsNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://namespace.lantmateriet.se/distribution/produkter/belagenhetsadress/v4.1")]
    [System.Xml.Serialization.XmlRootAttribute("Belagenhetsadress", Namespace="http://namespace.lantmateriet.se/distribution/produkter/belagenhetsadress/v4.1", IsNullable=false)]
    public partial class BelagenhetsadressType : AbstractFeatureType {
    
        private string objektidentitetField;
    
        private int objektversionField;
    
        private System.DateTime versionGiltigFranField;
    
        private bool versionGiltigFranFieldSpecified;
    
        private ObjektstatusType objektstatusField;
    
        private AdressplatsattributType adressplatsattributField;
    
        private AdressplatsnamnType adressplatsnamnField;
    
        private UtbytesobjektType itemField;
    
        private AdressplatsanmarkningType[] adressplatsanmarkningField;
    
        private AdressattAnlaggningType adressattAnlaggningField;
    
        private RegisterenhetsreferensType[] registerenhetsreferensField;
    
        private DistrikttillhorighetType distrikttillhorighetField;
    
        /// <remarks/>
        public string objektidentitet {
            get {
                return this.objektidentitetField;
            }
            set {
                this.objektidentitetField = value;
            }
        }
    
        /// <remarks/>
        public int objektversion {
            get {
                return this.objektversionField;
            }
            set {
                this.objektversionField = value;
            }
        }
    
        /// <remarks/>
        public System.DateTime versionGiltigFran {
            get {
                return this.versionGiltigFranField;
            }
            set {
                this.versionGiltigFranField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool versionGiltigFranSpecified {
            get {
                return this.versionGiltigFranFieldSpecified;
            }
            set {
                this.versionGiltigFranFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        public ObjektstatusType objektstatus {
            get {
                return this.objektstatusField;
            }
            set {
                this.objektstatusField = value;
            }
        }
    
        /// <remarks/>
        public AdressplatsattributType Adressplatsattribut {
            get {
                return this.adressplatsattributField;
            }
            set {
                this.adressplatsattributField = value;
            }
        }
    
        /// <remarks/>
        public AdressplatsnamnType Adressplatsnamn {
            get {
                return this.adressplatsnamnField;
            }
            set {
                this.adressplatsnamnField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Adressomrade", typeof(AdressomradeType))]
        [System.Xml.Serialization.XmlElementAttribute("Gardsadressomrade", typeof(GardsadressomradeType))]
        public UtbytesobjektType Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Adressplatsanmarkning")]
        public AdressplatsanmarkningType[] Adressplatsanmarkning {
            get {
                return this.adressplatsanmarkningField;
            }
            set {
                this.adressplatsanmarkningField = value;
            }
        }
    
        /// <remarks/>
        public AdressattAnlaggningType AdressattAnlaggning {
            get {
                return this.adressattAnlaggningField;
            }
            set {
                this.adressattAnlaggningField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Registerenhetsreferens")]
        public RegisterenhetsreferensType[] Registerenhetsreferens {
            get {
                return this.registerenhetsreferensField;
            }
            set {
                this.registerenhetsreferensField = value;
            }
        }
    
        /// <remarks/>
        public DistrikttillhorighetType Distrikttillhorighet {
            get {
                return this.distrikttillhorighetField;
            }
            set {
                this.distrikttillhorighetField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://namespace.lantmateriet.se/distribution/produkter/belagenhetsadress/v4.1")]
    [System.Xml.Serialization.XmlRootAttribute("BelagenhetsadressResponse", Namespace="http://namespace.lantmateriet.se/distribution/produkter/belagenhetsadress/v4.1", IsNullable=false)]
    public partial class BelagenhetsadressResponseType : AbstractFeatureType {
    
        private System.DateTime giltigVidField;
    
        private bool giltigVidFieldSpecified;
    
        private BelagenhetsadressMemberType[] belagenhetsadressMemberField;
    
        private AggregationType aggregationTypeField;
    
        private bool aggregationTypeFieldSpecified;
    
        /// <remarks/>
        public System.DateTime giltigVid {
            get {
                return this.giltigVidField;
            }
            set {
                this.giltigVidField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool giltigVidSpecified {
            get {
                return this.giltigVidFieldSpecified;
            }
            set {
                this.giltigVidFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BelagenhetsadressMember")]
        public BelagenhetsadressMemberType[] BelagenhetsadressMember {
            get {
                return this.belagenhetsadressMemberField;
            }
            set {
                this.belagenhetsadressMemberField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AggregationType aggregationType {
            get {
                return this.aggregationTypeField;
            }
            set {
                this.aggregationTypeField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool aggregationTypeSpecified {
            get {
                return this.aggregationTypeFieldSpecified;
            }
            set {
                this.aggregationTypeFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://namespace.lantmateriet.se/distribution/produkter/belagenhetsadress/v4.1")]
    public partial class BelagenhetsadressMemberType : AbstractFeatureMemberType {
    
        private BelagenhetsadressType belagenhetsadressField;
    
        /// <remarks/>
        public BelagenhetsadressType Belagenhetsadress {
            get {
                return this.belagenhetsadressField;
            }
            set {
                this.belagenhetsadressField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BelagenhetsadressMemberType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/gml/3.2")]
    public abstract partial class AbstractFeatureMemberType {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/gml/3.2")]
    public enum AggregationType {
    
        /// <remarks/>
        set,
    
        /// <remarks/>
        bag,
    
        /// <remarks/>
        sequence,
    
        /// <remarks/>
        array,
    
        /// <remarks/>
        record,
    
        /// <remarks/>
        table,
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MultiSurfaceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MultiCurveType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MultiPointType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/gml/3.2")]
    public abstract partial class AbstractGeometricAggregateType : AbstractGeometryType {
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PolygonType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/gml/3.2")]
    public abstract partial class AbstractSurfaceType : AbstractGeometricPrimitiveType {
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LineStringType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/gml/3.2")]
    public abstract partial class AbstractCurveType : AbstractGeometricPrimitiveType {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://namespace.lantmateriet.se/distribution/produkter/belagenhetsadress/v4.1")]
    public enum BelagenhetsadresstatusType {
    
        /// <remarks/>
        Reserverad,
    
        /// <remarks/>
        Gällande,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/gml/3.2")]
    [System.Xml.Serialization.XmlRootAttribute("posList", Namespace="http://www.opengis.net/gml/3.2", IsNullable=false)]
    public partial class DirectPositionListType {

        private double[] coordinates;

        [System.Xml.Serialization.XmlIgnore]
        public double[] Coordinates
        {

            get { return this.coordinates; }
            set { this.coordinates = value; }
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        public string Text
        {
            get
            {
                return Fastighetsrapport.Util.GeometryParser.ConvertDoubleArrayToString(this.coordinates);
            }
            set
            {
                this.coordinates = Fastighetsrapport.Util.GeometryParser.ConvertStringToDoubleArray(value);
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/gml/3.2")]
    [System.Xml.Serialization.XmlRootAttribute("LineString", Namespace="http://www.opengis.net/gml/3.2", IsNullable=false)]
    public partial class LineStringType : AbstractCurveType {
    
        private DirectPositionListType posListField;
    
        /// <remarks/>
        public DirectPositionListType posList {
            get {
                return this.posListField;
            }
            set {
                this.posListField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/gml/3.2")]
    [System.Xml.Serialization.XmlRootAttribute("Polygon", Namespace="http://www.opengis.net/gml/3.2", IsNullable=false)]
    public partial class PolygonType : AbstractSurfaceType {
    
        private AbstractRingPropertyType exteriorField;
    
        private AbstractRingPropertyType[] interiorField;
    
        /// <remarks/>
        public AbstractRingPropertyType exterior {
            get {
                return this.exteriorField;
            }
            set {
                this.exteriorField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("interior")]
        public AbstractRingPropertyType[] interior {
            get {
                return this.interiorField;
            }
            set {
                this.interiorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/gml/3.2")]
    [System.Xml.Serialization.XmlRootAttribute("exterior", Namespace="http://www.opengis.net/gml/3.2", IsNullable=false)]
    public partial class AbstractRingPropertyType {
    
        private LinearRingType itemField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LinearRing")]
        public LinearRingType Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/gml/3.2")]
    [System.Xml.Serialization.XmlRootAttribute("LinearRing", Namespace="http://www.opengis.net/gml/3.2", IsNullable=false)]
    public partial class LinearRingType : AbstractRingType {
    
        private DirectPositionListType posListField;
    
        /// <remarks/>
        public DirectPositionListType posList {
            get {
                return this.posListField;
            }
            set {
                this.posListField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/gml/3.2")]
    [System.Xml.Serialization.XmlRootAttribute("curveMember", Namespace="http://www.opengis.net/gml/3.2", IsNullable=false)]
    public partial class CurvePropertyType {
    
        private LineStringType itemField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LineString")]
        public LineStringType Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/gml/3.2")]
    [System.Xml.Serialization.XmlRootAttribute("surfaceMember", Namespace="http://www.opengis.net/gml/3.2", IsNullable=false)]
    public partial class SurfacePropertyType {
    
        private PolygonType itemField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Polygon")]
        public PolygonType Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/gml/3.2")]
    [System.Xml.Serialization.XmlRootAttribute("MultiPoint", Namespace="http://www.opengis.net/gml/3.2", IsNullable=false)]
    public partial class MultiPointType : AbstractGeometricAggregateType {
    
        private PointPropertyType[] pointMemberField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pointMember")]
        public PointPropertyType[] pointMember {
            get {
                return this.pointMemberField;
            }
            set {
                this.pointMemberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/gml/3.2")]
    [System.Xml.Serialization.XmlRootAttribute("MultiCurve", Namespace="http://www.opengis.net/gml/3.2", IsNullable=false)]
    public partial class MultiCurveType : AbstractGeometricAggregateType {
    
        private CurvePropertyType[] curveMemberField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("curveMember")]
        public CurvePropertyType[] curveMember {
            get {
                return this.curveMemberField;
            }
            set {
                this.curveMemberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/gml/3.2")]
    [System.Xml.Serialization.XmlRootAttribute("MultiSurface", Namespace="http://www.opengis.net/gml/3.2", IsNullable=false)]
    public partial class MultiSurfaceType : AbstractGeometricAggregateType {
    
        private SurfacePropertyType[] surfaceMemberField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("surfaceMember")]
        public SurfacePropertyType[] surfaceMember {
            get {
                return this.surfaceMemberField;
            }
            set {
                this.surfaceMemberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://namespace.lantmateriet.se/distribution/produkter/belagenhetsadress/v4.1")]
    [System.Xml.Serialization.XmlRootAttribute("IdRequest", Namespace="http://namespace.lantmateriet.se/distribution/produkter/belagenhetsadress/v4.1", IsNullable=false)]
    public partial class IdRequestType {
    
        private string[] idField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("id")]
        public string[] id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://namespace.lantmateriet.se/distribution/produkter/belagenhetsadress/v4.1")]
    [System.Xml.Serialization.XmlRootAttribute("GeometriRequest", Namespace="http://namespace.lantmateriet.se/distribution/produkter/belagenhetsadress/v4.1", IsNullable=false)]
    public partial class GeometriRequestType {
    
        private GeometryPropertyType geometriField;
    
        private int bufferField;
    
        private bool bufferFieldSpecified;
    
        /// <remarks/>
        public GeometryPropertyType Geometri {
            get {
                return this.geometriField;
            }
            set {
                this.geometriField = value;
            }
        }
    
        /// <remarks/>
        public int buffer {
            get {
                return this.bufferField;
            }
            set {
                this.bufferField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bufferSpecified {
            get {
                return this.bufferFieldSpecified;
            }
            set {
                this.bufferFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/gml/3.2")]
    public partial class GeometryPropertyType {
    
        private AbstractGeometryType abstractGeometryField;
    
        /// <remarks/>
        public AbstractGeometryType AbstractGeometry {
            get {
                return this.abstractGeometryField;
            }
            set {
                this.abstractGeometryField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://namespace.lantmateriet.se/distribution/produkter/belagenhetsadress/v4.1")]
    [System.Xml.Serialization.XmlRootAttribute("BelagenhetsadressreferensResponse", Namespace="http://namespace.lantmateriet.se/distribution/produkter/belagenhetsadress/v4.1", IsNullable=false)]
    public partial class BelagenhetsadressreferensResponseType {
    
        private BelagenhetsadressreferensType[] belagenhetsadressreferensField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Belagenhetsadressreferens")]
        public BelagenhetsadressreferensType[] Belagenhetsadressreferens {
            get {
                return this.belagenhetsadressreferensField;
            }
            set {
                this.belagenhetsadressreferensField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://namespace.lantmateriet.se/distribution/produkter/belagenhetsadress/v4.1")]
    public partial class BelagenhetsadressreferensType {
    
        private string objektidentitetField;
    
        private string beteckningField;
    
        /// <remarks/>
        public string objektidentitet {
            get {
                return this.objektidentitetField;
            }
            set {
                this.objektidentitetField = value;
            }
        }
    
        /// <remarks/>
        public string beteckning {
            get {
                return this.beteckningField;
            }
            set {
                this.beteckningField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://namespace.lantmateriet.se/distribution/produkter/belagenhetsadress/v4.1")]
    [System.Xml.Serialization.XmlRootAttribute("BeteckningResponse", Namespace="http://namespace.lantmateriet.se/distribution/produkter/belagenhetsadress/v4.1", IsNullable=false)]
    public partial class BeteckningResponseType {
    
        private object[] itemsField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Belagenhetsadressreferens", typeof(BelagenhetsadressreferensType))]
        [System.Xml.Serialization.XmlElementAttribute("beteckning", typeof(string))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
}